### ISSUE TITLE
issue with setting nginx_user

### ISSUE THREAD

**Issue by rbarabas** [savagegus/ansible-consul#105]
The nginx_user gets set improperly on RHEL and bootstrap provisioning fails unless nginx_user is set explicitly for this role in the play.

The problem exists here:

```
  - { role: franklinkim.nginx, when: consul_install_nginx == true and ansible_os_family == "Debian" }
  - { role: geerlingguy.nginx, when: consul_install_nginx == true and ansible_os_family == "RedHat" }
  - { role: joshualund.golang, when: consul_install_consul_cli == true }
```

The problem appears to be that franklinkim's nginx sets nginx_user in its default/main.yml:

```
🌀  grep nginx_user defaults/main.yml
nginx_user: www-data
```

Which remains loaded for the successive role (geerlingguy.nginx). The next nginx role finds this variable set and won't override it with the platform default, even if that was not explicitly set by the user, but the previously attempted role.

Not sure if there is a safer way to "probe" role loading without cluttering the main namespace. I'm eager to learn if there is.

**Comment by jimbydamonk** [comment]
On RHEL when I include the role I do something like this:

```
- name: Configure instance 
  hosts: all
  roles:
   - role: ansible-consul   
      consul_is_server: true
      consul_is_ui: true
      consul_install_dnsmasq: true
      consul_install_consulate: true
      consul_datacenter: "{{ region }}"
      consul_bootstrap: false 
      consul_node_name: "{{ inventory_hostname }}"
      consul_use_systemd: false
      consul_use_upstart: false
      consul_use_initd: true
      consul_ui_server_port: 8086
      consul_join_at_start: true
      nginx_user: nginx 
```
That seems to work for me.
