### ISSUE TITLE
Can it offer an option not to install nginx ? 

### ISSUE THREAD

**Issue by vpack** [savagegus/ansible-consul#144]
I am using this playbook for consul server and it works like magic - love that !!.

I am also using this playbook for consul client. It still installs nginx. Is there an option to override that?

**Comment by vpack** [comment]
I had my playbook setup as below. When I run ansible in a new amazon linux instance, it worked !! ( it skipped the nginx tasks).

I am new to Ansible, - I guess skipping each of the nginx tasks is the expected behavior when using conditional role dependencies in meta/main.yml.


consul-server-playbook.yml
```
  pre_tasks:
  - set_fact:
      ansible_distribution_major_version: "6"
      nginx_user: nginx
  vars:
    consul_use_upstart: false
    consul_install_nginx: false
```
