### ISSUE TITLE
Include example of automatic bootstrapping

### ISSUE THREAD

**Issue by trevorr** [savagegus/ansible-consul#169]
https://www.consul.io/docs/guides/bootstrapping.html:

> In versions of Consul prior to 0.4, bootstrapping was a more manual process. [...] Manual bootstrapping is not recommended as it is more error-prone than automatic bootstrapping with `-bootstrap-expect`.

The examples currently only show manual bootstrapping, and neglect to mention that the `-bootstrap` option is not safe to leave enabled once bootstrapping is complete. (They also show setting `-bootstrap` across all nodes, which is [not correct](https://www.consul.io/docs/guides/manual-bootstrap.html).) It took some trial and error and reading of the module code to get automatic bootstrapping to work:

```
- hosts: consul_public
  become: yes
  become_user: root
  vars:
    consul_version: 0.6.4
    consul_is_server: true
    consul_datacenter: dev
    consul_node_name: "{{ ansible_default_ipv4['address'] }}"
    consul_bind_address: "{{ ansible_default_ipv4['address'] }}"
    consul_bootstrap_expect: "{{ groups['consul_private'] | length }}"
    consul_servers: "{{ groups['consul_private'] }}"
    consul_join_at_start: true
    consul_retry_join: true
  roles:
    - ansible-consul
```

This example demonstrates using a public IP address for deployment via SSH, but configuring the Consul cluster to use private IP addresses (`ansible_default_ipv4` returns private IP addresses). It also uses a non-root account for SSH (which requires applying a fix for #146, such as PR #159, for recent Ansible versions). Finally, setting `consul_node_name`, `consul_servers`, `consul_join_at_start`, and `consul_retry_join` are all necessary for `consul_bootstrap_expect` to work.
